version: '3.7'
services:
  neightec-psql:
    container_name: neightec-psql
    ports:
      - '5481:5432'
    environment:
      - POSTGRESQL_PASSWORD=neightecpass
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:17
    restart: unless-stopped
    volumes:
      - 'neightec-psql-volume:/bitnami/postgresql'
      - ./postgresql/init-postgresql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      neightec-dev-env:
        ipv4_address: 172.90.1.81
  # neightec-mariadb:
  #   container_name: neightec-mariadb
  #   ports:
  #     - '3308:3306'
  #   image: mariadb:latest
  #   restart: unless-stopped
  #   environment:
  #     - MYSQL_USER=neight
  #     - MYSQL_PASSWORD=neightecpass
  #     - MYSQL_ROOT_PASSWORD=neightecpass
  #     - MYSQL_DATABASE=neightec-mariadb
  #   networks:
  #     neightec-dev-env:
  #       ipv4_address: 172.90.1.82
  neightec-redis:
    container_name: neightec-redis
    ports:
      - '6379:6379'
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass somePasswordRedis
    restart: unless-stopped
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=somePasswordRedis
    networks:
      neightec-dev-env:
        ipv4_address: 172.90.1.82
volumes:
  neightec-psql-volume:
    name: neightec-psql-data
  neightec-redis-volume:
    name: neightec-redis-data
    
networks:
  neightec-dev-env:
    ipam:
      driver: default
      config:
        - subnet: 172.90.1.0/24