debug=false
trace=false
# LOGGING
logging.config=classpath:log4j2.xml
# IDENTITY (ContextIdApplicationContextInitializer)
spring.application.name=Neight Tec Antivirus Server
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server.error.whitelabel.enabled=false
server.port=8080
server.servlet.context-path=/ntav-api
server.ssl.enabled=false
server.tomcat.max-swallow-size=-1
server.tomcat.secure=true
# MULTIPART (MultipartProperties)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.servlet.multipart.resolve-lazily=true
# ----------------------------------------
# DATA PROPERTIES
# ----------------------------------------
# LIQUIBASE (LiquibaseProperties)
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/database/changelog/db.changelog-project.xml
spring.liquibase.drop-first=false
spring.liquibase.default-schema=neight
spring.liquibase.contexts=dev
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#com.neightec.av-server.datasource.serverName=localhost
#com.neightec.av-server.datasource.portNumber=5480
#com.neightec.av-server.datasource.databaseName=neightec
com.neightec.av-server.datasource.url=jdbc:postgresql://localhost:5481/neight
com.neightec.av-server.datasource.driverClassName=org.postgresql.Driver
com.neightec.av-server.datasource.schema=neight
com.neightec.av-server.datasource.primary.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
com.neightec.av-server.datasource.username=neight
com.neightec.av-server.datasource.password=8qLKJbXuA9bwkNMreWb8
#com.neightec.av-server.primary.schema=neightec_data
#com.neightec.av-server.primary.username=neightec_user
#com.neightec.av-server.datasource.primary.password=cBgS^2mD#Ya}4DfXf
com.neightec.av-server.datasource.primary.poolName=neightec-pool
com.neightec.av-server.datasource.primary.maximumPoolSize=10
com.neightec.av-server.datasource.primary.maxLifetime=3600000
com.neightec.av-server.datasource.primary.connectionTimeout=1200000
com.neightec.av-server.datasource.primary.leakDetectionThreshold=60000

# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
# Possible values: create / create-drop / update / validate / none
spring.jpa.hibernate.ddl-auto=validate

# This is needed for Lazy JPA entities to be loaded by jackson. Default is true,
# but Spring will issue a warning if not set explicitly
spring.jpa.open-in-view=true
# Defines the maximum join depth for EAGER relationships in Hibernate
# This parameter can be used to quickly get rid of "MariaDB can only handle 61 tables in a join" exceptions.
# Another approach is to check every connection relationships and set them to LAZY where it makes sense.
spring.jpa.properties.hibernate.max_fetch_depth=0
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.format_sql=true

# neightec av server file path config
com.neightec.av-server.filepathsconfig.filesignaturecsv=classpath:files/file-signature.csv
com.neightec.av-server.filepathsconfig.filesignaturexlsx=classpath:files/file-signature.xlsx

management.endpoints.web.cors.allow-credentials=true
management.endpoints.web.cors.allowed-headers=X-XSRF-TOKEN, origin, content-type, Authorization
management.endpoints.web.cors.allowed-methods=GET, POST, PUT, DELETE
management.endpoints.web.cors.allowed-origins=http://localhost:4201
management.endpoints.web.cors.exposed-headers=X-XSRF-TOKEN, Authorization

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.clientId=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.clientSecret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirectUri={baseUrl}/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=email, profile
